//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeepleHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockedUsers
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public string ComplaintTitle { get; set; }
        public string ComplaintText { get; set; }
        public int BlockedByAdminId { get; set; }
        public System.DateTime BlockedAt { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> UnblockedByAdminId { get; set; }
        public Nullable<System.DateTime> UnblockedAt { get; set; }
    
        public virtual Admins Admins { get; set; }
        public virtual Admins Admins1 { get; set; }
        public virtual Users Users { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
