//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeepleHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardGames
    {
        public BoardGames()
        {
            this.Registrations = new HashSet<Registrations>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> MinPlayers { get; set; }
        public Nullable<int> MaxPlayers { get; set; }
    
        public virtual ICollection<Registrations> Registrations { get; set; }
    }
}
