//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeepleHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registrations
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    
        public virtual BoardGames BoardGames { get; set; }
        public virtual Users Users { get; set; }
    }
}
