//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeepleHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerGameAssignments
    {
        public int Id { get; set; }
        public int WorkerId { get; set; }
        public int GameId { get; set; }
        public int AssignedByAdminId { get; set; }
        public System.DateTime AssignedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> RemovedDate { get; set; }
    
        public virtual Admins Admins { get; set; }
        public virtual BoardGames BoardGames { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
