//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeepleHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerComplaints
    {
        public int Id { get; set; }
        public int WorkerId { get; set; }
        public int UserId { get; set; }
        public int ComplaintId { get; set; }
        public string ComplaintText { get; set; }
        public System.DateTime ComplaintDate { get; set; }
        public bool IsReviewed { get; set; }
        public Nullable<System.DateTime> ReviewedAt { get; set; }
        public Nullable<int> ReviewedByAdminId { get; set; }
    
        public virtual Admins Admins { get; set; }
        public virtual Complaints Complaints { get; set; }
        public virtual Users Users { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
